package Parser;
//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################

import SymbolTable.Attribute;
import SymbolTable.Type;
import SymbolTable.Use;
import SyntacticTree.SyntacticTree;

import java.util.List;

/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ParserVal
{
    /**
     * integer value of this 'union'
     */
    public int ival;

    /**
     * double value of this 'union'
     */
    public double dval;

    /**
     * string value of this 'union'
     */
    public String sval;

    /**
     * object value of this 'union'
     */
    public Object obj;

    /**
     * syntacticTree value of this 'union'
     */
    public SyntacticTree tree;

    /**
     * list attribute value of this 'union'
     */
    public List<Attribute> attributes;

    /**
     * attributesSetteable value of this 'union'
     */
    public List<String> attributesSetteable;

    /**
     * use value of this 'union'
     */
    public Type type;


//#############################################
//## C O N S T R U C T O R S
//#############################################
    /**
     * Initialize me without a value
     */
    public ParserVal()
    {
    }
    /**
     * Initialize me as an int
     */
    public ParserVal(int val)
    {
        ival=val;
    }

    /**
     * Initialize me as a double
     */
    public ParserVal(double val)
    {
        dval=val;
    }

    /**
     * Initialize me as a string
     */
    public ParserVal(String val)
    {
        sval=val;
    }

    /**
     * Initialize me as an Object
     */
    public ParserVal(Object val)
    {
        obj=val;
    }

    /**
     * Initialize me as an SyntacticTree
     */
    public ParserVal(SyntacticTree val)
    {
        tree=val;
    }


    /**
     * Initialize me as an Attribute
     */
    public ParserVal(List<Attribute> val)
    {
        attributes=val;
    }

    /**
     * Initialize me as an Type
     */
    public ParserVal(Type val)
    {
        type=val;
    }


}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
